### ISSUE TITLE
Error Importing pandas_market_calendars

### ISSUE THREAD

**Issue by iamdavie** [conda-forge/pandas_market_calendars-feedstock#17]
I seem to running into errors while trying to import `pandas_market_calendars`
I am using `pandas_market_calendars   1.7` from conda -forge channel and the following gives an error as follows:

> ---------------------------------------------------------------------------
`import pandas_market_calendars as mcal`
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_2308/3439585815.py in <module>
      1 import pandas as pd
----> 2 import pandas_market_calendars as mcal
      3 import numpy as np
      4 import matplotlib.pyplot as plt
      5 import matplotlib.markers as mkz

~\Miniconda3\envs\pydavie\lib\site-packages\pandas_market_calendars\__init__.py in <module>
     17 import pkg_resources
     18 
---> 19 from .calendar_registry import get_calendar, get_calendar_names
     20 from .calendar_utils import convert_freq, date_range, merge_schedules
     21 # TODO: is the below needed? Can I replace all the imports on the calendars with ".market_calendar"

~\Miniconda3\envs\pydavie\lib\site-packages\pandas_market_calendars\calendar_registry.py in <module>
     19 from .exchange_calendar_bse import BSEExchangeCalendar
     20 from .exchange_calendar_tase import TASEExchangeCalendar
---> 21 from .trading_calendars_mirror import *
     22 
     23 

~\Miniconda3\envs\pydavie\lib\site-packages\pandas_market_calendars\trading_calendars_mirror.py in <module>
      9 from datetime import time
     10 from .market_calendar import MarketCalendar
---> 11 import trading_calendars
     12 
     13 

~\Miniconda3\envs\pydavie\lib\site-packages\trading_calendars\__init__.py in <module>
     14 # limitations under the License.
     15 
---> 16 from .trading_calendar import TradingCalendar
     17 from .calendar_utils import (
     18     clear_calendars,

~\Miniconda3\envs\pydavie\lib\site-packages\trading_calendars\trading_calendar.py in <module>
     31 import toolz
     32 
---> 33 from .calendar_helpers import (
     34     NP_NAT,
     35     compute_all_minutes,

~\Miniconda3\envs\pydavie\lib\site-packages\trading_calendars\calendar_helpers.py in <module>
      4 NANOSECONDS_PER_MINUTE = int(6e10)
      5 
----> 6 NP_NAT = np.array([pd.NaT], dtype=np.int64)[0]
      7 
      8 

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'

**Comment by trendelkampschroer** [comment]
This is just the feed stock for the package, please raise the issue at https://github.com/rsheftel/pandas_market_calendars
instead. 

You can also try `exchange_calendars` package https://github.com/gerrymanoim/exchange_calendars which should provide similar functionality.

**Comment by iamdavie** [comment]
Thank you for your response!!
